docs/source/examples.rst
src/volue/mesh/examples/working_with_link_relations.py

Add link relation example

---

pyproject.toml

Stable `protobuf` version 4 was released last year.

Update dependencies version requirements

---

docs/source/versions.rst
pyproject.toml
src/volue/mesh/_attribute.py

Fix parsing empty (not connected) time series attributes

---

src/volue/mesh/_authentication.py
src/volue/mesh/_base_connection.py
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/examples/connect_using_external_access_token.py

* Added `with_external_access_token` function to `Connection` class.
* Added `connect_using_external_access_token.py` example
Documentation will be added in separate PR.

OAuth (external access token) connection implementation and example

---

pyproject.toml
src/volue/mesh/_object.py

Handle root objects

---

src/volue/mesh/examples/timeseries_search.py

Add 2 more ways of reading time series attributes.

Extend `timeseries_search` example

---

docs/source/versions.rst

Squash info about latest 1.2.1 version.

Update versions doc page

---

.github/workflows/development.yml
.github/workflows/usage.yml
src/volue/mesh/_base_session.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/tests/test_rating_curve.py

Versions must be sorted in `update_rating_curve_versions`

---

docs/source/mesh_modelling.rst
pyproject.toml
src/volue/mesh/_base_session.py
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/examples/traverse_model.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/tests/test_mesh_objects.py

Add `list_models` and tests. Update documentation and example on traversing the complete model.

Add `list_models`

---

.github/workflows/development.yml
.github/workflows/usage.yml

Official release 2.10.0 (2.10.0.11)

Switch to 2.10.0

---

docs/source/mesh_concepts.rst

Add Mesh session link to Mesh concept list in the documentation

---

src/volue/mesh/_attribute.py
src/volue/mesh/examples/traverse_model.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/tests/test_attributes.py

Followup of https://github.com/Volue/energy-mesh/issues/4256

Add bottom top traversal support

---

README.md
src/volue/mesh/_attribute.py

Add info to README.md what are the requirements of the current master version of SDK.
Update TODOs after switching to 2.11

Changes after switching to Mesh 2.11

---

docs/source/hydsim.rst
docs/source/index.rst
docs/source/versions.rst

Resolves https://github.com/Volue-Public/energy-mesh-python/issues/394.

Document HydSim methods

---

docs/source/versions.rst
pyproject.toml

* Bump version to 1.6.0-dev.
* Add entry to versions.rst.

Bump version and mark it as dev/pre-release.

---

.github/workflows/development.yml
.github/workflows/install_dev_env/action.yml
.github/workflows/long_tests.yml
.github/workflows/pages.yml
.github/workflows/usage.yml
docs/source/versions.rst
pyproject.toml

Support Python 3.12.
Drop Python 3.8.

Python 3.12 support

---

src/volue/mesh/examples/search_calculation_expressions.py

As mentioned in https://github.com/Volue/energy-mesh/issues/4709#issuecomment-1927582286.
Refactoring the way we import `_get_connection_info` is out of the scope of this PR.

Add example with searching calculation expressions

---

src/volue/mesh/_common.py
src/volue/mesh/_mesh_id.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/type/resources.proto

Adjust to changes introduced to Mesh server in https://github.com/Volue/energy-mesh/pull/4919.

Handle `MeshId` move from core.proto to type/resources.proto

---

.gitignore

Proto files split coming next.

General git ignore rules for proto binaries

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
pyproject.toml
src/volue/mesh/_attribute.py
src/volue/mesh/_base_connection.py
src/volue/mesh/_base_session.py
src/volue/mesh/_common.py
src/volue/mesh/_object.py
src/volue/mesh/_timeseries_resource.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/core/v1alpha/resources.proto
src/volue/mesh/proto/model_definition/v1alpha/model_definition.proto
src/volue/mesh/proto/model_definition/v1alpha/resources.proto
src/volue/mesh/tests/test_mesh_objects.py

* core.proto is split into:
* core/v1alpha/resources.proto 
* model_definition/v1alpha/model_definition.proto
* model_definition/v1alpha/resources.proto 
* Switch to intermediate Mesh build 2.13.0.1761 - for testing

Handle core.proto split

---

pyproject.toml
src/volue/mesh/_base_connection.py
src/volue/mesh/_base_session.py
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/core/v1alpha/resources.proto
src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto

Handle hydsim RPCs extraction that was done in https://github.com/Volue/energy-mesh/pull/4995.

Handle hydsim RPCs extraction from core.proto to separate service

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
src/volue/mesh/_attribute.py
src/volue/mesh/_base_connection.py
src/volue/mesh/_base_session.py
src/volue/mesh/_connection.py
src/volue/mesh/_timeseries_resource.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/core/v1alpha/resources.proto
src/volue/mesh/proto/model_definition/v1alpha/model_definition.proto
src/volue/mesh/proto/model_definition/v1alpha/resources.proto
src/volue/mesh/tests/test_timeseries_resource.py

Handle unit of measurement proto changes

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
src/volue/mesh/_base_session.py
src/volue/mesh/_common.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/core/v1alpha/resources.proto

Remove return_no_attributes

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
src/volue/mesh/_attribute.py
src/volue/mesh/proto/model_definition/v1alpha/model_definition.proto
src/volue/mesh/proto/model_definition/v1alpha/resources.proto
src/volue/mesh/tests/test_attributes.py
src/volue/mesh/tests/test_mesh_objects.py

Implement proto `Tag` changes - resolves #405 
Update proto files to Mesh v2.13.0.4 RC.
Use the above Mesh version for tests.

Implement tag changes

---

src/volue/mesh/__init__.py
src/volue/mesh/_common.py
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/examples/run_inflow_calculation.py
src/volue/mesh/examples/run_simulation.py
src/volue/mesh/proto/core/v1alpha/core.proto
src/volue/mesh/proto/core/v1alpha/resources.proto
src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto
src/volue/mesh/proto/type/resources.proto

Resolves https://github.com/Volue-Public/energy-mesh-python/issues/396.

Add logs to HydSim responses

---

docs/source/hydsim.rst
src/volue/mesh/_base_session.py
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto

Resolves https://github.com/Volue-Public/energy-mesh-python/issues/397.
See also https://github.com/Volue/energy-mesh/pull/5164.

Add methods for getting MC files

---

src/volue/mesh/tests/test_attributes.py
src/volue/mesh/tests/test_authentication.py
src/volue/mesh/tests/test_examples.py

Drop usage of `is False` and `is True`.

Minor refactoring

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
README.md

Switch to official Mesh 2.13.1 build

---

docs/source/versions.rst
pyproject.toml

* Add entry to versions in the documentation
* Set version to stable 1.7 (no dev suffix)

Release version 1.7

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add feature and bug report issue templates

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
docs/source/versions.rst
pyproject.toml
src/volue/mesh/_attribute.py
src/volue/mesh/_authentication.py
src/volue/mesh/_base_connection.py
src/volue/mesh/_base_session.py
src/volue/mesh/_common.py
src/volue/mesh/_connection.py
src/volue/mesh/_object.py
src/volue/mesh/_timeseries_resource.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/calc/common.py
src/volue/mesh/proto/auth/v1alpha/auth.proto
src/volue/mesh/proto/calc/v1alpha/calc.proto
src/volue/mesh/proto/config/v1alpha/config.proto
src/volue/mesh/proto/model/v1alpha/model.proto
src/volue/mesh/proto/model/v1alpha/resources.proto
src/volue/mesh/proto/model_definition/v1alpha/model_definition.proto
src/volue/mesh/proto/model_definition/v1alpha/resources.proto
src/volue/mesh/proto/session/v1alpha/session.proto
src/volue/mesh/proto/time_series/v1alpha/time_series.proto
src/volue/mesh/tests/test_calculation.py
src/volue/mesh/tests/test_session.py
src/volue/mesh/tests/test_timeseries.py

Adjust to Mesh 2.14

---

src/volue/mesh/__init__.py

To make intelisense happy and enable:

Add simple attribute to init

---

.github/workflows/usage.yml

Switch to newer Ubuntu in GitHub actions

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
src/volue/mesh/tests/test_mesh_objects.py

And adjust expected error messages in tests.

Switch to latest Mesh master (2.15 pre-release)

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
src/volue/mesh/tests/test_timeseries.py

Adjust the test due to https://github.com/Volue/energy-mesh/pull/5721, use latest Mesh master

Adjust the test to the latest Mesh RPC error handling update

---

pyproject.toml

See #485.
Issue was resolved in newer versions: https://github.com/grpc/grpc/issues/37178.

Revert limiting max grpcio and grpcio-tools version

---

src/volue/mesh/tests/test_model.py

Newly added tests are sporadically failing. The reason is the way Mesh updates other sessions when one of them commits data. 
**It is not guaranteed that committed data from one session is immediately propagated to other sessions.** E.g.:
```python
session1 = connection.create_session()
session1.open()
session2 = connection.create_session()
session2.open()
new_object1 = session1.create_object(ownership_attribute, "NewPlant")
new_object2 = session2.create_object(ownership_attribute, "NewPlant")
session1.commit()
with pytest.raises(
grpc.RpcError,
match="session "
+ str(session2.session_id)
+ " is corrupt due to changes done by some other session, rollback your changes to fix your session",
):
session2.commit()
```
This might fail in 2 ways:
* The expected way is to get the session …

Adjust tests to Mesh session update mechanism

---

pyproject.toml

grpcio and grpcio-tools to current latest versions - 1.66.1
protobuf to the one supported/used by grpc tools - 5.27.2
Means to WA/resolve #503

Limit grpc and protobuf

---

src/volue/mesh/tests/test_timeseries.py

This should work with both the new and the old message.

Fix test ref. changed error

---

docs/source/versions.rst
src/volue/mesh/examples/search_calculation_expressions.py

Found by accident when looking at #505

Fix `search_calculation_expressions.py` example

---

src/volue/mesh/examples/check_duplicated_time_series.py

Add a script that checks and prints (if any) duplicated physical or virtual time series connected to Mesh time series attributes.

Add check_duplicated_time_series.py

---

docs/source/faq.rst
docs/source/versions.rst
pyproject.toml

* Update versions in the documentation
* Set version to stable 1.11 (no dev suffix)

Release version 1.11

---

docs/source/versions.rst
pyproject.toml

Bump version and mark it as dev/pre-release

---

src/volue/mesh/examples/timeseries_search.py

Fix description in the search example

---

docs/source/api.rst
docs/source/conf.py
docs/source/mesh_availability.rst
docs/source/mesh_concepts.rst
docs/source/versions.rst
src/volue/mesh/_connection.py
src/volue/mesh/aio/_connection.py
src/volue/mesh/availability/__init__.py
src/volue/mesh/availability/_availability.py
src/volue/mesh/availability/_availability_aio.py
src/volue/mesh/availability/_base_availability.py

Add availability docs

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml
docs/source/versions.rst
src/volue/mesh/proto/availability/v1alpha/availability.proto
src/volue/mesh/tests/test_availability.py

* Switch to Mesh 2.18.0.5
* Update 1.13.0-dev Mesh compatible version to 2.18 - due to availability functionality

Switch to Mesh 2.18 RC

---

.github/workflows/install_dev_env/action.yml
.github/workflows/usage.yml

Switch to latest Mesh 2.18 RC.

Switch to Mesh 2.18.0.8

---

docs/source/versions.rst
pyproject.toml

* Update versions in the documentation
* Set version to stable 1.13 (no dev suffix)

Release version 1.13

---

docs/source/installation.rst

Add latest versions with regards to limitations specified in current `[build-system]` section in pyproject.toml

docs: add more info to offline installation

---

src/volue/mesh/tests/test_mesh_objects.py

~~Should start working when Python tests start to run on the newest mesh.~~
Should start working.

Fix number of expected attributes in simple thermal model
