Volue-Public/energy-mesh-python

- .github/workflows/development.yml
- .github/workflows/usage.yml
- docs/source/faq.rst
- docs/source/index.rst
- docs/source/versions.rst
- pyproject.toml
~~Put on hold - due to current incompatibility of pip/distutil (distutil is needed for kerberos on Ubuntu) with Python 3.10.~~
~~For windows github actions are working correctly for python 3.10.~~
We are supporting Python 3.10 now.
> Python 3.10 support

- pyproject.toml
- src/volue/mesh/_base_session.py
- src/volue/mesh/examples/working_with_link_relations.py
- src/volue/mesh/examples/working_with_model.py
- src/volue/mesh/examples/working_with_rating_curves.py
- src/volue/mesh/tests/test_authentication.py
- src/volue/mesh/tests/test_performance.py
- src/volue/mesh/tests/test_rating_curve.py
- src/volue/mesh/tests/test_relations.py
- src/volue/mesh/tests/test_session.py
- src/volue/mesh/use_cases/use_cases.py
`lint.yml` github page is using latest black version, meanwhile in `pyproject.toml` in dev section we were limited to version max 22.
Latest `black` version 23 introduces some changes to the style, so 10 files have some minor changes in this PR.
> Update black auto-formatter

- .github/workflows/usage.yml
When building `volue.mesh` package we are getting:
```
ModuleNotFoundError: No module named 'poetry'
```
See [failed GitHub action](https://github.com/Volue-Public/energy-mesh-python/actions/runs/4184884198/jobs/7251151637).
Either install poetry in build environment or downgrade pip. 
It first appeared on latest pip version 23, released 31.01.2023.
> Fix usage GitHub action for Python 3.10 on WSL

- src/volue/mesh/examples/authorization.py
- src/volue/mesh/examples/get_version.py
Starting with Python 3.10 a deprecation warning is emitted in 2 examples when using `asyncio.get_event_loop()`.
> Fix `DeprecationWarning: There is no current event loop`

- .github/workflows/usage.yml
Reverts Volue-Public/energy-mesh-python#341
Meanwhile pip had an update. I want to check if this is still needed.
> Revert "Fix usage GitHub action for Python 3.10 on WSL"

- src/volue/mesh/_attribute.py
Some simple attributes like `UtcDateTime` attribute may have null values. In such case there are no `value`s in the proto message. In such cases the `value` in Python should be set to `None`.
> Handle `SimpleAttribute`s without any values

- .github/workflows/usage.yml
- docs/source/mesh_session.rst
- pyproject.toml
- src/volue/mesh/_base_session.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/tests/test_session.py
For each session create a new thread that after 2.5 mins will send `ExtendSession` RPC to Mesh server.
Mark the thread as daemon so it won't block Python's application exit.
The assumption is that the application will have concurrently open rather limited number of sessions, so the overhead of having separate worker thread for each of them will be low.
For async sessions provide the main event loop to the worker thread that will submit `_extend_lifetime` as coroutine and wait until it finishes.
I also added tests that will increase 2-3x times our tests running duration. Most likely I'll deselect them from running per PR in another PR.
> Automatically extend session lifetime

- .github/workflows/install_dev_env/action.yml
- .github/workflows/long_tests.yml
- README.md
Extract common part of installing poetry, building Mesh Python SDK and installing Mesh service to `install_dev_env`.
Long tests will be scheduled to run nightly on `master` branch only if there were some changes merged.
> Add action for long tests

- src/volue/mesh/_base_session.py
`DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead`
Deprecated in Python 3.10.
> Set daemon property directly

- pyproject.toml
Winkerberos 0.9.1 has pre-built wheels for python 3.11.
Change also the dependency version constraints from caret `^` to `>=`, so that we will fetch the next version of winkerberos once it is released. Winkerberos 0.10.0 will support Python 3.12.
> Bump winkerberos to 0.9.1

- .github/workflows/install_dev_env/action.yml
- .github/workflows/usage.yml
- src/volue/mesh/tests/test_session.py
Official release 2.11.0 (2.11.0.13)
> Switch to 2.11

- pyproject.toml
We don't support Python 3.12 at this time. This makes for a much more pleasant error.
> Constrain Python to ">=3.8, <3.12"

- docs/source/examples.rst
- src/volue/mesh/_connection.py
- src/volue/mesh/examples/run_simulation.py
- src/volue/mesh/proto/core/v1alpha/core.proto
- No asynchronous implementation as that'll be mildly different.
- No docs.
- One example, no tests. Python unit tests for simulations aren't really feasible as things stand.
- Tested manually using the example.
- No handling of log or dataset returns, the current server doesn't send those.
- No handling of resolution.
- No handling of scenarios, which is currently not supported on the server.
- Interface subject to change.
See https://github.com/Volue/energy-sim/issues/742.
> experimental: add synchronous run_simulation

- docs/source/examples.rst
- src/volue/mesh/_connection.py
- src/volue/mesh/examples/run_inflow_calculation.py
- src/volue/mesh/proto/core/v1alpha/core.proto
- No asynchronous implementation as that'll be mildly different.
- No docs.
- Only example, no tests. Python unit tests for inflow calculations aren't really feasible as things stand.
- Tested manually using the example.
- No handling of log or dataset returns, the current server doesn't send those.
- Interface subject to change.
See https://github.com/Volue/energy-sim/issues/742.
> experimental: add synchronous run_inflow_calculation

- src/volue/mesh/_connection.py
- src/volue/mesh/examples/run_simulation.py
`CaseGroup/CaseName` is established syntax used in various UIs, Optimal Gateway, and Automation Framework. As discussed in https://github.com/Volue/energy-sim/issues/742#issuecomment-1811942095.
There's an argument for more user friendly error handling here, but I think this is API compatible with a future improvement, and I want to get this API break done ASAP. For now you'll get a `ValueError` if the split doesn't split.
Closes https://github.com/Volue-Public/energy-mesh-python/issues/398.
> Use `CaseGroup/CaseName` to refer to hydsim cases

- docs/source/examples.rst
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/examples/run_inflow_calculation_async.py
- src/volue/mesh/examples/run_simulation_async.py
Includes hydro simulation and inflow calculation. PQ curve generation will be added separately when server support is available. This API is very much subject to change for the near term future.
See https://github.com/Volue/energy-sim/issues/742.
Closes https://github.com/Volue-Public/energy-mesh-python/issues/395.
> experimental: add async HydSim methods

- src/volue/mesh/_base_session.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- Add abstract method to `_base_session.py`.
- Add barebones docstring. Definitely not final.
- Unify request preparation in `_prepare_run_simulation_request`.
Part of https://github.com/Volue-Public/energy-mesh-python/issues/394.
> Refactor run_simulation

- src/volue/mesh/_authentication.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
After adding OAuth support, the fake auth used for internal purposes only stopped working.
> Fix fake auth

- src/volue/mesh/_base_session.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- Add abstract method to `_base_session.py`.
- Add barebones docstring. Definintely not final.
- Unify request preparation in `_prepare_run_inflow_calculation_request`.
> Refactor run_inflow_calculation

- .github/workflows/install_dev_env/action.yml
- .github/workflows/usage.yml
Use Mesh 2.12 official build for testing in GitHub actions.
> Use Mesh 2.12 in GitHub actions

- pyproject.toml
When using new poetry on GitHub action Ubuntu runner we're getting:
```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
> Fix GitHub action pages

- docs/source/examples.rst
- docs/source/versions.rst
- pyproject.toml
* Add entry to versions in the documentation
* Set version to stable 1.6 (no dev suffix)
* Remove reference to no longer existing example: `write_timeseries_points_async.py`
> Release version 1.6

- src/volue/mesh/_common.py
- src/volue/mesh/_timeseries.py
- src/volue/mesh/tests/test_calculation.py
> Handle `MIN30` resolution

- src/volue/mesh/_attribute.py
As stated in the removed TODO message:
```
```
> Changes in handling attribute's owner

- src/volue/mesh/_base_session.py
- src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto
gRPC compatibility with Mesh v2.14. Does not affect the Python API.
See https://github.com/Volue/energy-mesh/pull/5179.
> hydsim.proto: split requests and responses

- src/volue/mesh/__init__.py
- src/volue/mesh/_base_session.py
- src/volue/mesh/_common.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/examples/run_inflow_calculation.py
- src/volue/mesh/examples/run_simulation.py
- src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto
A HydSim dataset is a representation of data used in a hydro simulation or inflow calculation. The HydSim team sometimes uses datasets when diagnosing customer issues. Traditionally datasets have been stored on the Mesh server if an attribute with a directory path is non-empty in the Mesh model.
A problem with this setup is that most users shouldn't have access to the Mesh server. When a regular user wants to report a HydSim issue they may need help from a superuser to extract the datasets from the Mesh server. This is not ideal.
Going forward we want Mesh clients that run simulations and inflow calculations to handle datasets on the client side so that it's possible for regular users to access datasets, as well as more convenient for users that might have Mesh access.
This patch adds …
> Add support for getting HydSim datasets

- src/volue/mesh/tests/test_performance.py
- src/volue/mesh/tests/test_timeseries.py
With newer pandas we're getting:
```
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
```
> Fix pandas warning

- docs/source/versions.rst
- src/volue/mesh/_base_session.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/examples/run_inflow_calculation.py
- src/volue/mesh/examples/run_simulation.py
- src/volue/mesh/proto/hydsim/v1alpha/hydsim.proto
When implementing run_simulation and run_inflow_calculation I used our predefined protobuf time series resolutions for simulation and inflow calculation resolution. This is not correct and those might run on resolutions we don't allow for time series.
Update proto to use
https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/duration.proto, which is used by the Mesh server starting with v2.14.0.
See https://github.com/Volue/energy-mesh/issues/5305 (internal).
See https://github.com/Volue/energy-mesh/pull/5317 (internal).
> Fix resolution for simulation and inflow calc

- .github/workflows/install_dev_env/action.yml
- .github/workflows/usage.yml
- docs/source/versions.rst
- pyproject.toml
* Add entry to versions in the documentation
* Unify versioning scheme of supported Mesh server versions in previous Mesh Python SDK versions.
* Use latest Mesh 2.14 RC
* Set version to stable 1.8 (no dev suffix)
> Release version 1.8

- src/volue/mesh/tests/test_authentication.py
Occasionally[^1] we are getting new token with the same expiration date as the previous one.
```
test_authentication.py:98: AssertionError
def test_auth_metadata_plugin_obtains_correctly_new_token_after_delete(
auth_metadata_plugin,
):
"""Check if after deleting access token a new one is correctly obtained."""
assert auth_metadata_plugin.is_token_valid()
previous_token = auth_metadata_plugin.token
previous_token_expiration_date = auth_metadata_plugin.token_expiration_date
#time.sleep(0.001)
auth_metadata_plugin.delete_access_token()
auth_metadata_plugin.get_token()
new_token = auth_metadata_plugin.token
new_token_expiration_date = auth_metadata_plugin.token_expiration_date
assert auth_metadata_plugin.is_token_valid()
assert new_token is not None
assert new_token is not previous_token
> …
```
> Add sleep in one auth test

- src/volue/mesh/examples/write_timeseries_points.py
When preparing for Python SDK demo I realized there is no example with setting time zone for time series points when writing.
The thing is that usual `tzlocal()` does not work:
```
AttributeError: 'NoneType' object has no attribute 'replace'
```
* Provide in comment example of using different time zone than UTC.
* Use more concise approach for generating a sequence of timestamps.
> Extend write ts points example

- src/volue/mesh/_attribute.py
- src/volue/mesh/_common.py
Partially resolves #470 - specifically the "empty" target objects for versioned link relations, see: https://github.com/Volue/energy-mesh/issues/5425.
> Handle "empty" link relation target objects

- .github/workflows/install_dev_env/action.yml
- .github/workflows/usage.yml
- docs/source/versions.rst
- src/volue/mesh/_base_session.py
- src/volue/mesh/_common.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/examples/working_with_link_relations.py
- src/volue/mesh/proto/model/v1alpha/model.proto
- src/volue/mesh/proto/model/v1alpha/resources.proto
- src/volue/mesh/proto/model_definition/v1alpha/model_definition.proto
- src/volue/mesh/proto/model_definition/v1alpha/resources.proto
- src/volue/mesh/proto/time_series/v1alpha/time_series.proto
- src/volue/mesh/tests/test_mesh_objects.py
- src/volue/mesh/tests/test_relations.py
Make current Python SDK compatible with the upcoming Mesh 2.15.
Changes:
* **BREAKING CHANGE**: Rename `update_versioned_link_relation_attribute` to `update_versioned_one_to_one_link_relation_attribute`
* Update proto files.
* Add tests and extend example to show versioned link relations with empty target objects.
> Adjust to Mesh 2.15

- docs/source/versions.rst
- src/volue/mesh/_base_session.py
- src/volue/mesh/_connection.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/examples/working_with_link_relations.py
- src/volue/mesh/tests/test_relations.py
* Added new function `update_versioned_one_to_many_link_relation_attribute`
* Added tests
* Extended example
> Support for updating versioned one-to-many link relations

- docs/source/api.rst
Those are defined as class methods on base class and by default the inherited members are not included in the documentation,
Still we want to add only those specific methods from `Connection` class.
> Include connection methods in API documentation

- pyproject.toml
Temp WA for extra logs that can mess log parsing systems, it was introduces with grpcio 1.65.0. E.g. when running get_version.py example:
```
Synchronous get version:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1720778120.895832    6892 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_client, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
99.0.0+0
I0000 00:00:1720778120.904418    6892 work_stealing_thread_pool.cc:269] WorkStealingThreadPoolImpl::Quiesce
Asynchronous get version:
99.0.0+0
I0000 00:00:1720778120.910360    6892 work_stealing_thread_pool.cc:269] …
```
> Limit max grpcio and grpcio-tools version

- docs/source/installation.rst
> Add offline installation docs

- README.md
- docs/source/versions.rst
Instead of specifying required/compatible Mesh server version in both: versions.rst and README.md, define it only in versions.rst and provide a link in README.md.
> Documentation improvements for versions and requirements

- docs/source/versions.rst
In 1.9 there were introduced API adjustments for Mesh 2.15
> Set upper bound of compatible Mesh version for 1.8

- docs/source/versions.rst
- pyproject.toml
* Update versions in the documentation
* Set version to stable 1.10 (no dev suffix)
* Leave Mesh version as it is since minimal supported Mesh version didn't change.
As a bonus use code-block:: bash to avoid ugly formatting.
Before:
Now:
> Release version 1.10

- pyproject.toml
One of the steps to address #526 
With poetry-core 2.0.0 there was a breaking change introduced:
https://python-poetry.org/blog/announcing-poetry-2.0.0#consistent-include-behavior
This affected the way we included generated python proto stubs. Namely by default if a VCS is used by default ignored files will be excluded. To avoid this we need to explicitly set needed files in `include` section. Include has higher priority than exclude rules.
For more info see: https://python-poetry.org/docs/pyproject#exclude-and-include
However, until now we didn't use `format` option. With poetry-core 2.0.0 if format is not specified the file is only included in sdist, previously it was sdist and wheel.
This PR makes the include section poetry-core 2.0.0 compatible, but also limits the max poetry-core …
> fix: set upper bound for required poetry-core version

- docs/source/faq.rst
Description of ways to address #526 issue.
> docs: add entry to FAQ about broken package issue

- .github/workflows/usage.yml
For Python 3.12 we recently started getting:
```
E: Unable to locate package python3.12-distutils
E: Couldn't find any package by glob 'python3.12-distutils'
E: Couldn't find any package by regex 'python3.12-distutils'
```
Install `distutils` only for Python 3.9. For newer versions we can live without this.
> fix: env for python 3.12 tests

- .github/workflows/usage.yml
- docs/source/versions.rst
- pyproject.toml
- src/volue/mesh/tests/test_attributes.py
- src/volue/mesh/tests/test_mesh_id.py
- src/volue/mesh/tests/test_mesh_objects.py
- src/volue/mesh/tests/test_relations.py
* Exclude tests and examples from the package
* Use `poetry.group.dev.dependencies`[^1]. `poetry.dev-dependencies` is deprecated in Poetry 2.0. 
[^1]: This is the proper way of defining dev deps since Poetry 1.2.0. See: See: https://python-poetry.org/docs/1.8/managing-dependencies/
> chore: do not include tests and examples in the package

- .github/workflows/install_dev_env/action.yml
- .github/workflows/usage.yml
- src/volue/mesh/tests/test_timeseries.py
* Switch to current Mesh 2.17 master build
* Adjust tests to changes with requested time series ID. If requesting points for a time series attribute we no longer return ID (and time series key) of connected physical time series (if any). Instead we return the same ID as in the request.
See example:
* Time series attribute `TsAtt` is connected to physical time series with time series key equal 100
* Client requests time series points for `TsAtt` providing e.g. time series path like: "Model/MyModel/MyObject.TsAtt"
* For Mesh server versions <= 2.16 we returned time series points with ID, path and time series key of to the physical time series.
* _ID_OF_PHYSICAL_TIME_SERIES_
* Path = "Resource/MyResourceCatalog/MyPhysicalTimeseries"
* Key = 100
* Starting with Mesh 2.17 we return time series …
> chore: switch to current Mesh 2.17 master build

- docs/source/versions.rst
- src/volue/mesh/_base_session.py
- src/volue/mesh/_common.py
- src/volue/mesh/_connection.py
- src/volue/mesh/_timeseries.py
- src/volue/mesh/aio/_connection.py
- src/volue/mesh/tests/test_timeseries.py
Starting from Mesh 2.17 when an empty time series is read (e.g.: break point time series with no values), instead of raising an `ValueError` with message `No data in time series reply for the given interval`, we will now return `volue.mesh.Timeseries` instance with an empty Arrow table and start/end timestamps set to `None`. Other time series metadata like resolution will be set as usual.
This PR needs new Mesh server release to pass the new test.
> Support for new way of sending empty time series

- src/volue/mesh/tests/test_session.py
It was extended for Mesh 2.11 (in #381 PR). See issue: https://github.com/Volue/energy-mesh/issues/4471.
In Mesh 2.15.3 it was resolved, lower the limit back to 1 second to speed up tests.
**Wait for switching to Mesh 2.15.1 in Mesh Python SDK**
> Lower sleep time in session test

- src/volue/mesh/_mesh_id.py
- src/volue/mesh/tests/test_relations.py
In Mesh 2.18 there is a change that fixes returning non-empty attribute values when a versioned 1:1 link relation attribute doesn't have any entries. This change affects 2 tests in Mesh Python SDK.
Temporarily handle 2 behaviors: for new Mesh 2.18 and older Mesh versions.
Once we have available a nightly, engineering, etc. build of Mesh 2.18 ready, we'll switch to just one, new behavior.
> temporary fix for relation tests

- docs/source/versions.rst
- src/volue/mesh/aio/_connection.py
It caused sporadic `test_mesh_objects_async` test fails.
> fix: Async `delete_object` was missing an `await` on an internal async call

- src/volue/mesh/tests/test_relations.py
We switched to Mesh 2.18 with #555
> chore: address ToDos in tests

- .github/workflows/development.yml
- .github/workflows/long_tests.yml
- .github/workflows/usage.yml
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/quickstart.rst
- docs/source/versions.rst
- pyproject.toml
There was a need to bump max grpcio-tools version. We had upper limit == 1.66.1, and since 1.66.2 there was support for 3.13.
As a result of this bump we need also to bump the corresponding protobuf version[^1].
Latest stable grpcio-tools version available in pip is 1.71.0, but it uses protobuf 5.29.0 - which was yanked,
See: 
* https://github.com/grpc/grpc/blob/v1.71.0/third_party/protobuf.patch
* https://pypi.org/project/protobuf/5.29.0/
Previous grpcio-tools version that uses other protobuf version is 1.68.1 and the corresponding protobuf is 5.28.1.
See: https://github.com/grpc/grpc/blob/v1.68.1/third_party/protobuf.patch
Resolves #541 
[^1]: See issue #503 for more info.
> Support Python 3.13

- pyproject.toml
Starting from grpcio==1.68.0 in some cases the gRPC connection is aborted, e.g. when there are 2 concurrent sessions open and there is some pause/sleep between requests. This is causing the `test_sessions_lifetime_auto_extension` test to fail with:
```
"IOCP/Socket: Connection aborted (An established connection was aborted by the software in your host machine.
-- 10053)"
```
I need to dig deeper to find out the root cause. For now revert to version(s) that seem to work correctly.
> limit versions of grpc related deps

- src/volue/mesh/_timeseries.py
- src/volue/mesh/examples/write_timeseries_points.py
Enrich example with pandas DataFrame serving as input for writing time series.
> chore: extend `write_timeseries_points` example with pandas DataFrame use case
